included:
  - Sources
  - Tests
disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - identifier_name
  - nesting
  - type_body_length

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/  Copyright © \d{4} Ninh\. All rights reserved\.
                    \/\/
